### ISSUE TITLE
Airdrop tokens to not whitelisted users

### ISSUE THREAD

**Issue by markholdex** [holdex/tsp-smart_contracts#8]
https://github.com/holdex/tsp-smart_contracts/blob/e48af1682a85bfe6b245af06e48af64dcc9ab92b/contracts/Crowdsale.sol#L468

**Comment by ericobi** [comment]
@markholdex 
```
/**
	function sendTokens
	
	Airdrop tokens to any whitelisted address.
	Parameters: 
	_investor - wallet address
	_amount - amount of tokens to be transferred
	*/
```

`sendTokens` function says that it sends to any whitelisted address meaning that the function is written correctly.

**Comment by markholdex** [comment]
@ericobi sorry but this repository is outdated and not used. As you can see the issue was opened in 2019. Please look for assignments in the core repository: https://github.com/holdex/holdex-venture-studio/issues?q=is:issue+is:open+label:goal
